AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Prog4 First TD - SAM Template

Parameters:
  Environment:
    Type: String
    Default: dev
    Description: Environment name
  
  ServiceName:
    Type: String
    Default: prog4-first-td
    Description: Service name

Globals:
  Function:
    Timeout: 60
    MemorySize: 512
    Runtime: java21
    Environment:
      Variables:
        SERVICE_NAME: !Ref ServiceName
        ENVIRONMENT: !Ref Environment

Resources:
  ApplicationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

Outputs:
  ApplicationRole:
    Description: Application IAM Role
    Value: !Ref ApplicationRole
