



spring.datasource.url=jdbc:postgresql://ep-dawn-cake-a2k5fgba.eu-central-1.aws.neon.tech:5432/neondb?sslmode=require&channel_binding=disable
spring.datasource.username=neondb_owner
spring.datasource.password=npg_zku3NDIeUC4p

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.hikari.connection-timeout=30000